### ISSUE TITLE
Getting AMQ119005: Exception in Netty transport during benchmarking

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/artemis-image#10]
When benchmarking a single queue shard, the connector service sometimes disconnects and I get the following in the broker log:

13:35:58,874 INFO  [org.apache.activemq.artemis.integration.amqp] Connection exception: AMQ119005: Exception in Netty transport
13:35:58,874 INFO  [org.apache.activemq.artemis.protocol.amqp.client.ProtonClientConnectionManager] Connection /172.30.184.251:55673 exception: AMQ119005: Exception in Netty transport
13:35:58,876 WARN  [org.apache.activemq.artemis.core.client] AMQ212037: Connection failure has been detected: AMQ119005: Exception in Netty transport [code=INTERNAL_ERROR]
13:35:58,876 WARN  [org.apache.activemq.artemis.core.server] AMQ222061: Client connection failed, clearing up resources for session 9e82e8ba-c137-11e6-8ea9-0242ac110002
13:35:58,877 WARN  [org.apache.activemq.artemis.core.server] AMQ222107: Cleared up resources for session 9e82e8ba-c137-11e6-8ea9-0242ac110002
13:35:58,877 INFO  [org.apache.activemq.artemis.protocol.amqp.client.ProtonClientConnectionManager] Connection /172.30.184.251:55673 destroyed
13:36:08,874 INFO  [org.apache.activemq.artemis.integration.amqp] Connection destroyed, reconnecting
13:36:13,875 INFO  [org.apache.activemq.artemis.integration.amqp] Starting connector
13:36:13,881 INFO  [org.apache.activemq.artemis.protocol.amqp.client.ProtonClientConnectionManager] Connection /172.30.184.251:55673 created

**Comment by lulf** [comment]
Stack trace:


13:52:18,734 INFO  [org.apache.activemq.artemis.integration.amqp] Connection exception: AMQ119005: Exception in Netty transport: ActiveMQInternalErrorException[errorType=INTERNAL_ERROR message=AMQ119005: Exception in Netty transport]
        at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.exceptionCaught(ActiveMQChannelHandler.java:93) [artemis-core-client-1.5.1.jar:1.5.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:266) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1301) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:914) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:99) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:140) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_111]
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) [rt.jar:1.8.0_111]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) [rt.jar:1.8.0_111]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) [rt.jar:1.8.0_111]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) [rt.jar:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) [rt.jar:1.8.0_111]
        at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:277) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        ... 6 more
13:52:18,734 INFO  [org.apache.activemq.artemis.integration.amqp] Stack trace: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:277)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)

**Comment by lulf** [comment]
I've not seen this since then, and  it was perhaps a symptom of the other bugs fixed related to the frame error. Closing for now.
